import { test, expect } from "@playwright/test";

const MOCK_PREDICT_RESPONSE = {
  prediction: 1,
  churn_probability: 0.8234,
  retention_risk: "High",
};

const MOCK_SCRIPT_RESPONSE = {
  script: "[Generated by LLM] Thank you for your loyalty. Let me apply a 10% discount to your next bill.",
};

const MOCK_HEALTH_RESPONSE = {
  status: "healthy",
  model_loaded: true,
  model_path: "models/churn_model.pkl",
};

test.describe("Enterprise Churn Prediction Flow", () => {
  test.beforeEach(async ({ page }) => {
    await page.route("**/health", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(MOCK_HEALTH_RESPONSE),
      });
    });
    await page.route("**/predict", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(MOCK_PREDICT_RESPONSE),
      });
    });
    await page.route("**/generate_retention_script", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(MOCK_SCRIPT_RESPONSE),
      });
    });
  });

  test("navigates to parameters, submits form, and displays analysis results", async ({ page }) => {
    await page.goto("/");
    await expect(page.locator("h1")).toContainText("Enterprise Churn Engine");

    await page.getByText("Enter Engine").click();
    await page.waitForURL("**/parameters");
    await expect(page.locator("h1")).toContainText("Input Engine");

    await page.selectOption("#field-Gender", "Male");
    await page.selectOption("#field-SeniorCitizen", "No");
    await page.selectOption("#field-Partner", "Yes");
    await page.selectOption("#field-Dependents", "No");
    await page.fill("#field-tenure", "12");
    await page.selectOption("#field-Contract", "Month-to-Month");
    await page.selectOption("#field-InternetService", "Yes");
    await page.selectOption("#field-OnlineSecurity", "Yes");
    await page.selectOption("#field-TechSupport", "No");
    await page.fill("#field-MonthlyCharges", "75.0");
    await page.fill("#field-TotalCharges", "900.0");

    await page.getByText("Analyze").click();

    await page.waitForURL("**/analysis", { timeout: 15000 });
    await expect(page.locator("h1")).toContainText("Results Terminal");

    await expect(page.getByText("High")).toBeVisible();
    await expect(page.getByText("82.3")).toBeVisible();
    await expect(page.getByText("Churn Probability")).toBeVisible();
    await expect(page.getByText("Risk Classification")).toBeVisible();
    await expect(page.getByText("LLM")).toBeVisible();
  });

  test("displays error on backend failure", async ({ page }) => {
    await page.route("**/predict", async (route) => {
      await route.fulfill({
        status: 500,
        contentType: "application/json",
        body: JSON.stringify({ detail: "Internal server error" }),
      });
    });
    await page.route("**/health", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(MOCK_HEALTH_RESPONSE),
      });
    });

    await page.goto("/parameters");
    await page.fill("#field-tenure", "12");
    await page.fill("#field-MonthlyCharges", "75.0");
    await page.getByText("Analyze").click();

    await expect(page.locator("text=Internal server error")).toBeVisible({
      timeout: 10000,
    });
  });
});
