"""Tree SHAP extraction for the LightGBM churn model.

How the engine produces feature attributions
--------------------------------------------
LightGBM's ``booster.predict(X, pred_contrib=True)`` returns a
``(n_samples, n_features + 1)`` matrix where every column is a
per-feature log-odds contribution to the model's prediction and the
final column is the bias term (the mean log-odds over the training
data). Mathematically, for any row:

    sum(per_feature) + bias == logit(predict_proba(row))

to within float precision. The API's frontend renders these as a
horizontal bar panel sorted by ``|magnitude|``, so the highest-impact
churn drivers float to the top of the list.

The retention script endpoint (``/generate_retention_script``) takes
the top SHAP driver reasons as the ``reasons`` field of its request
body and asks the configured LLM provider to write a 2-sentence agent
script. The LLM output is prefixed with ``[Generated by LLM]``; a
missing API key or a failed LLM call is caught and routed to a labelled
static fallback so the endpoint is never allowed to raise.

Every public function in this module returns ``None`` on failure so
the prediction endpoints can keep working even if SHAP fails.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Eight contributors explain ~85% of typical churn decisions without
# overwhelming the UI.
DEFAULT_TOP_K = 8


def _humanize_category(value: str) -> str:
    """Turn a sanitized category token into a display label."""
    s = value.replace("_", " ").strip()
    if not s:
        return s
    # Training categories use a space ("Month to Month") but the FE
    # display convention uses a hyphen ("Month-to-Month"). Other
    # categories are already in their human form.
    return s.replace("Month to Month", "Month-to-Month")


def _reverse_col_map() -> Dict[str, str]:
    """Build a reverse lookup from sanitized model column back to API field name."""
    from src.feature_engineering import col_map

    reverse: Dict[str, str] = {}
    for api_field, dataset_col in col_map().items():
        sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", dataset_col)
        reverse[sanitized] = api_field
    return reverse


def _label_feature(sanitized_name: str, reverse_map: Dict[str, str]) -> str:
    """Resolve a sanitized column name to a human-readable label.

    1. Direct lookup in the reverse column map (e.g. ``Senior_Citizen`` -> ``SeniorCitizen``).
    2. One-hot split: ``<Base>_<Category>`` -> ``<pretty base>: <humanized category>``.
    3. Pass through.
    """
    if sanitized_name in reverse_map:
        return reverse_map[sanitized_name]

    if "_" in sanitized_name:
        base, _, category = sanitized_name.partition("_")
        pretty_base = _PRETTY_BASE.get(base, base)
        return f"{pretty_base}: {_humanize_category(category)}"

    return sanitized_name


# Pretty-print overrides for one-hot column bases that should be
# displayed with spaces rather than concatenated camel-case. Entries
# where the key already matches the value are no-ops and are
# omitted.
_PRETTY_BASE: Dict[str, str] = {
    "SeniorCitizen": "Senior Citizen",
    "PhoneService": "Phone Service",
    "MultipleLines": "Multiple Lines",
    "InternetService": "Internet Service",
    "OnlineSecurity": "Online Security",
    "OnlineBackup": "Online Backup",
    "DeviceProtection": "Device Protection",
    "TechSupport": "Tech Support",
    "StreamingTV": "Streaming TV",
    "StreamingMovies": "Streaming Movies",
    "StreamingMusic": "Streaming Music",
    "PaperlessBilling": "Paperless Billing",
    "PaymentMethod": "Payment Method",
    "UnlimitedData": "Unlimited Data",
    "Under30": "Under 30",
    "ReferredAFriend": "Referred a Friend",
    "InternetType": "Internet Type",
}


def _get_booster(pipeline: Any) -> Optional[Any]:
    """Return the underlying LightGBM Booster from a fitted pipeline.

    Supports a bare ``LGBMClassifier``, a sklearn ``Pipeline`` whose final
    step is one, and a calibrated/meta-estimator that wraps one.
    """
    if pipeline is None:
        return None
    candidate = pipeline

    if hasattr(candidate, "steps") and isinstance(getattr(candidate, "steps", None), list) and candidate.steps:
        candidate = candidate.steps[-1][1]

    # Check ``booster_`` BEFORE the meta-estimator unwrap loop, otherwise
    # MagicMock-wrapped classifiers in tests get misidentified.
    direct = getattr(candidate, "booster_", None)
    if direct is not None:
        return direct

    for attr in ("estimator", "base_estimator"):
        nested = getattr(candidate, attr, None)
        if nested is None:
            continue
        nested_booster = getattr(nested, "booster_", None)
        if nested_booster is not None:
            return nested_booster

    if hasattr(candidate, "_Booster"):
        return candidate._Booster

    return None


def explain_prediction(
    pipeline: Any,
    df: pd.DataFrame,
    top_k: int = DEFAULT_TOP_K,
) -> Optional[List[Dict[str, Any]]]:
    """Top-k SHAP attributions for a single-row frame, or None on failure.

    The caller is responsible for aligning ``df.columns`` to the booster's
    expected features.
    """
    if pipeline is None or df is None or df.empty or top_k <= 0:
        return None

    validated = _validate_contribs(pipeline, df)
    if validated is None:
        return None
    per_feature, _ = validated

    try:
        reverse_map = _reverse_col_map()
    except Exception:  # noqa: BLE001
        reverse_map = {}

    return _format_contributions(per_feature, df, reverse_map, top_k)


def _validate_contribs(
    pipeline: Any, df: pd.DataFrame
) -> Optional[tuple]:
    """Run the booster, coerce to ``np.ndarray``, and slice off the bias.

    Returns ``(per_feature, n_features)`` on success, ``None`` on any
    failure (no booster, booster raised, bad shape, column mismatch).
    """
    raw = _compute_raw_contribs(pipeline, df)
    if raw is None:
        return None
    n_features = len(df.columns)
    per_feature = _extract_per_feature(raw, n_features)
    if per_feature is None:
        return None
    return per_feature, n_features


def _compute_raw_contribs(
    pipeline: Any, df: pd.DataFrame
) -> Optional[np.ndarray]:
    """Invoke the booster's ``pred_contrib`` and coerce to a 2-D ``ndarray``.

    Returns ``None`` and logs a ``SHAP_*`` tag on any failure.
    """
    booster = _get_booster(pipeline)
    if booster is None or not hasattr(booster, "predict"):
        logger.info("SHAP_UNAVAILABLE: pipeline has no booster")
        return None

    try:
        contribs = booster.predict(df, pred_contrib=True)
    except Exception as exc:  # noqa: BLE001 — SHAP must never crash the API
        logger.warning("SHAP_COMPUTATION_FAILED: %s", exc)
        return None

    try:
        contribs = np.asarray(contribs)
    except Exception:
        return None

    if contribs.ndim != 2 or contribs.shape[0] == 0:
        logger.info("SHAP_BAD_SHAPE: %s", getattr(contribs, "shape", None))
        return None
    return contribs


def _extract_per_feature(
    contribs: np.ndarray, n_features: int
) -> Optional[np.ndarray]:
    """Slice off the bias column (or pass through if it's already absent)."""
    # ``pred_contrib`` returns (n_samples, n_features + 1) where the final
    # column is the bias term. Older builds or 1D returns may omit it.
    if contribs.shape[1] == n_features + 1:
        return contribs[0, :n_features]
    if contribs.shape[1] == n_features:
        return contribs[0]
    logger.info(
        "SHAP_COLUMN_MISMATCH: contribs=%s expected=%d",
        contribs.shape,
        n_features,
    )
    return None


def _format_contributions(
    per_feature: np.ndarray,
    df: pd.DataFrame,
    reverse_map: Dict[str, str],
    top_k: int,
) -> List[Dict[str, Any]]:
    """Sort by ``|magnitude|``, take top-k, and build the API-facing records."""
    row_values = df.iloc[0]
    safe = np.where(np.isfinite(per_feature), per_feature, 0.0)
    abs_mag = np.abs(safe)
    order = np.argsort(-abs_mag, kind="stable")
    k = min(int(top_k), len(df.columns))

    out: List[Dict[str, Any]] = []
    for idx in order[:k]:
        col_name = str(df.columns[int(idx)])
        contribution = float(safe[int(idx)])
        raw_value = row_values[col_name] if col_name in row_values.index else None
        try:
            if pd.isna(raw_value):
                display_value: Any = None
            else:
                display_value = raw_value.item() if hasattr(raw_value, "item") else raw_value
        except Exception:
            display_value = None

        out.append({
            "feature": _label_feature(col_name, reverse_map),
            "value": display_value,
            "magnitude": round(abs(contribution), 4),
            "direction": "up" if contribution >= 0 else "down",
        })
    return out
